import Head from "next/head";
import type { AppProps } from "next/app";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { QueryClient, QueryClientProvider } from "react-query";

import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { Layout } from "@/components/Layout";
import "@/styles/globals.scss";

const queryClient = new QueryClient();

function MyApp({ Component, pageProps }: AppProps) {
  const { pathname, push } = useRouter();

  return (
    <QueryClientProvider client={queryClient}>
      <Head>
        <title>DEMO Streaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/streaming.png" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </QueryClientProvider>
  );
}

export default MyApp;
