import type { NextPage } from "next";
import Head from "next/head";

import { Content } from "@/components/Content";

const Series: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DEMO Streaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/streaming.png" />
      </Head>

      <Content>
        <main>Oops, something went wrong...</main>
      </Content>
    </div>
  );
};

export default Series;
