import type { NextPage } from "next";
import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { TextButton } from "@/components/TextButton";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>DEMO Streaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/streaming.png" />
      </Head>

      <main className={styles.main}></main>
    </div>
  );
};

export default Home;
