import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import styles from "@/styles/Home.module.scss";
import { PopularTitleCard } from "@/components/PopularTitleCard";
import { Content } from "@/components/Content";

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>DEMO Streaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/streaming.png" />
      </Head>
      <Content>
        <main className={styles.main}>
          <PopularTitleCard
            onClick={() => {
              router.push("/movies");
            }}
            type="Movies"
          />
          <PopularTitleCard
            onClick={() => {
              router.push("/series");
            }}
            type="Series"
          />
        </main>
      </Content>
    </div>
  );
};

export default Home;
