import type { NextPage } from "next";
import Head from "next/head";

const Movies: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DEMO Streaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/streaming.png" />
      </Head>

      <main>Movie</main>
    </div>
  );
};

export default Movies;
