import type { NextPage } from "next";
import Head from "next/head";
import { useQuery } from "react-query";

import { Content } from "@/components/Content";

const Movies = () => {
  const { isLoading, error, data } = useQuery("repoData", () =>
    fetch("./sample.json").then((res) => res.json())
  );

  console.log(data);

  if (isLoading) return "Loading...";

  if (error) return "Oops, something went wrong ";

  return (
    <div>
      <Head>
        <title>DEMO Streaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/streaming.png" />
      </Head>

      <Content>
        <main className="overflow-hidden">
          <ul>
            {data.entries.map((i) => (
              <li key={i.id}>{i.title}</li>
            ))}
          </ul>
        </main>
      </Content>
    </div>
  );
};

export default Movies;
